id: PerformanceProfiler
version: 0.0.2
description: <__trans phrase="Recored performace profile.">
author_name: Six Apart Ltd.
author_link: https://www.movabletype.org/

config_settings:
  PerformanceProfilerProfilers:
    default: KYTProf
  PerformanceProfilerPath:
    default: ""
  PerformanceProfilerFrequency:
    default: 10
  PerformanceProfilerMaxFiles:
    default: 1000

callbacks:
  MT::App::CMS::init_app: $PerformanceProfiler::MT::Plugin::PerformanceProfiler::init_app
  build_file_filter: $PerformanceProfiler::MT::Plugin::PerformanceProfiler::build_file_filter
  build_page: $PerformanceProfiler::MT::Plugin::PerformanceProfiler::build_page
  take_down: $PerformanceProfiler::MT::Plugin::PerformanceProfiler::take_down
